-- BulkAF Supabase Schema
-- Im Supabase Dashboard -> SQL Editor einfügen und ausführen.

create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  weight numeric not null,
  goal_weight numeric not null,
  goal_date date not null,
  height numeric not null,
  age numeric not null,
  gender text not null check (gender in ('m','w')),
  activity numeric not null,
  created_at timestamptz default now()
);

alter table profiles enable row level security;

create policy "Users manage own profile"
  on profiles for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null default current_date,
  weight numeric not null,
  created_at timestamptz default now()
);

alter table weight_logs enable row level security;

create policy "Users manage own weight logs"
  on weight_logs for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
